require("busted")

insulate("should see system confdir", function()
	setup(function()
		xx = require("uci")
		print("setup system uci.confdir = " .. tostring(xx.get_confdir()))
		--xx.set_confdir("/home/karlp/src/owrt_private_feeds/hatred/confdir")
	end)
	teardown(function()
                print("teardown system uci.confdir = " .. tostring(xx.get_confdir()))
	end)
	it("do styuff", function()
		require("src.blah")
		assert.are.same("from_system_config", uci_get_first("busted", "fishy", "hatred"))
	end)
end)
